### ISSUE TITLE
Página é recarregada qdo atualiza um resultado

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app-frontend#10]
Depois de alterar o texto e clicar no "verdinho" a página acaba sendo carregada depois de alguns segundos.

Aparentemente há um request muito longo no endpoint
http://172.17.6.84/sislegis/rest/reuniaos/findByData?data=08%2F31%2F2015
que leva mais de 1 minuto

**Comment by gcdelgado** [comment]
Conversa em 09/10 via Slack:

gcdelgado [5:37 PM] 
@konopacki e @rafael.coutinho  conversei com o @theoziran a respeito da issue#10 (refresh após atualizar a proposição). Achamos melhor deixá-la para outra milestone por 2 motivos:
1. Para corrigir será necessário mudar uma estrutura relativamente grande, pois o frontend hoje considera toda a área da listagem de proposições como um único 'módulo', e o padrão do angular é atualizar todo este módulo após disparar os eventos.
2. Já estamos prestes a substituir a interface, portanto o esforço de criar esta estrutura de outra forma poderia se concentrar já na nova interface, evitando retrabalho.

gcdelgado [5:40 PM]
o que acham?

konopacki [7:46 PM] 
Fala @gcdelgado , considerando que teremos um esforço de atualização de interface nessa sprint, será que não conseguimos mante-la, mas pro final?

konopacki [7:47 PM]
Digo, faze-la ao mesmo tempo que o ajuste de interface?

gcdelgado [8:04 PM] 
@konopacki: acredito que a nova UI já deve nascer sem este problema - @theoziran e @thsl podem fazer a estrutura com módulos mais bem divididos, certo? e aí se precisar mudar algo no backend, eu já faço, talvez possa ser nessa sprint mesmo, vamos tentar?
