### ISSUE TITLE
O último comentário associado a proposição deveria ter sido incluído na listagem de busca de proposição, é ali que ele será útil para não reincluir proposições fora de competência.

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/sislegis-app-frontend#25]
![uploads/08fb1253-aaea-4bae-9c48-e81ce6d472d3/sislegis_comment.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F08fb1253-aaea-4bae-9c48-e81ce6d472d3%2Fsislegis_comment.png)

**Comment by rafaelcoutinho** [comment]
movido para sprint 15.11.01
